[package]
name = "tlsn-verifier"
authors = ["TLSNotary Team"]
description = "A library for the TLSNotary verifier"
keywords = ["tls", "mpc", "2pc"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.6"
edition = "2021"

[features]
default = []

[dependencies]
tlsn-common = { workspace = true, features = ["tee"] }
tlsn-core = { workspace = true, features = ["tee"] }
tlsn-tls-core = { workspace = true }
tlsn-tls-tee = { workspace = true }

serio = { workspace = true, features = ["compat"] }
uid-mux = { workspace = true, features = ["serio"] }

derive_builder = { workspace = true }
futures = { workspace = true }
opaque-debug = { workspace = true }
rand = { workspace = true }
signature = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
web-time = { workspace = true }

httparse = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
zeroize = { version = "1.8.1" }
serde = { workspace = true }
serde_json = { workspace = true }