[package]
name = "tlsn-common"
description = "Common code shared between tlsn-prover and tlsn-verifier"
version = "0.1.0-alpha.5"
edition = "2021"

[features]
default = ["tracing"]
tracing = ["uid-mux/tracing"]

[dependencies]
tlsn-utils-aio.workspace = true

derive_builder.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
uid-mux.workspace = true

semver = "1.0"

[dev-dependencies]
rstest.workspace = true
