[package]
name = "tlsn-common"
description = "Common code shared between tlsn-prover and tlsn-verifier"
version = "0.1.0-alpha.5"
edition = "2021"

[features]
default = []

[dependencies]
mpz-share-conversion.workspace = true
mpz-garble.workspace = true
mpz-garble-core.workspace = true
mpz-ot.workspace = true
mpz-ole.workspace = true
mpz-core.workspace = true
mpz-common.workspace = true

futures.workspace = true
serio = { workspace = true, features = ["codec", "bincode"] }
uid-mux = { workspace = true, features = ["serio"] }
tracing.workspace = true
