[package]
name = "tlsn-common"
description = "Common code shared between tlsn-prover and tlsn-verifier"
version = "0.1.0-alpha.6"
edition = "2021"

[features]
default = []

[dependencies]
mpz-common = { workspace = true }
mpz-garble = { workspace = true }
mpz-ot = { workspace = true }

derive_builder = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serio = { workspace = true, features = ["codec", "bincode"] }
thiserror = { workspace = true }
tracing = { workspace = true }
uid-mux = { workspace = true, features = ["serio"] }

once_cell = "1.19"
semver = "1.0"

[dev-dependencies]
rstest.workspace = true
